project_id = "qtmqkggfnpksdqsfkncx"

[functions.market-data]
verify_jwt = false

[functions.stock-coach]
verify_jwt = false

[functions.market-news]
verify_jwt = false

[functions.education]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.news-api]
verify_jwt = false

[functions.fred-data]
verify_jwt = false

[functions.pulse-tutor]
verify_jwt = false

[functions.stock-research]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-trial-expiry]
verify_jwt = false

[functions.fundamentals]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false
