project_id = "qtmqkggfnpksdqsfkncx"

[functions.market-data]
verify_jwt = false

[functions.stock-coach]
verify_jwt = false

[functions.market-news]
verify_jwt = false

[functions.education]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false